aiVersion: v1
kind: Secret
metadata:
  name: gnresolver
  namespace: gn
type: Opaque
data:
  db.user: Z25h # gna
  db.user.password: Z25hcGFzcw== # gnapass
  db.cluster.replication.user: cmVwbA== # repl
  db.cluster.replication.user.password: cmVwbHBhc3M= #replpass
  db.pool.users: Z25hOmduYXBhc3M= # gna:gnapass
  db.pool.pcp.user: cGNwX3VzZXI= #pcp_user
  db.pool.pcp.password: cGNwX3Bhc3M= #pcp_pass

