---
apiVersion: v1
kind: Service
metadata:
  name: gnresolver-db-master-service
  namespace: gn
  labels:
    app: gnresolver
    tier: backend
    type: master
    node: "1"
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: gnresolver
    tier: backend
    type: master
    node: "1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gnresolver-db-master
  namespace: gn
spec:
  replicas: 1
  template:
    metadata:
      name: gresolver-db-master
      labels:
        app: gnresolver
        tier: backend
        type: master
        node: "1"
    spec:
      volumes:
        - name: gnresolver-db-master-vol
          persistentVolumeClaim:
            claimName: gnresolver-pvc
      containers:
        -
          name: gnresolver-db-master
          image: paunin/postgresql-cluster-pgsql
          env: # those variables are not secret as it's just initial state of DB
            -
              name: "NODE_ID"
              value: "1"
            -
              name: "NODE_NAME"
              value: "node1"
            -
              name: "CLUSTER_NODE_NETWORK_NAME"
              value: "gnresolver-db-master-service"
            -
              name: "CONFIGS"
              valueFrom:
                configMapKeyRef:
                  name: gnresolver
                  key: db.configs
            -
              name: "REPMGR_WAIT_POSTGRES_START_TIMEOUT"
              valueFrom:
                configMapKeyRef:
                  name: gnresolver
                  key: db.repmgr.timeout

            # Work DB
            - name: "POSTGRES_DB"
              valueFrom:
                configMapKeyRef:
                  name: gnresolver
                  key: db.database
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: gnresolver
                  key: db.user
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: gnresolver
                  key: db.user.password
            - name: "PGDATA"
              valueFrom:
                configMapKeyRef:
                  name: gnresolver
                  key: db.pgdata


            # Cluster configs
            - name: "CLUSTER_NAME"
              valueFrom:
                configMapKeyRef:
                  name: gnresolver
                  key: db.cluster.name
            - name: "REPLICATION_DB"
              valueFrom:
                configMapKeyRef:
                  name: gnresolver
                  key: db.cluster.replication.db
            - name: "REPLICATION_USER"
              valueFrom:
                secretKeyRef:
                  name: gnresolver
                  key: db.cluster.replication.user
            - name: "REPLICATION_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: gnresolver
                  key: db.cluster.replication.user.password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath:  /var/lib/postgresql/data
              name: gnresolver-db-master-vol
