---
apiVersion: v1
kind: Service
metadata:
  name: gnresolver-db-slave1-service
  namespace: gn
  labels:
    app: gnresolver
    tier: backend
    type: slave
    node: "2"
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: gnresolver
    tier: backend
    type: slave
    node: "2"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gnresolver-db-slave1
  namespace: gn
spec:
  replicas: 1
  template:
    metadata:
      name: gresolver-db-slave1
      labels:
        app: gnresolver
        tier: backend
        type: slave
        node: "2"
    spec:
      volumes:
        - name: gnresolver-db-slave-vol
          emptyDir: {}
      containers:
        -
          name: gnresolver-db-slave1
          image: paunin/postgresql-cluster-pgsql
          env: # those variables are not secret as it's just initial state of DB
            -
              name: "REPLICATION_PRIMARY_HOST"
              value: "gnresolver-db-master-service"
            -
              name: "NODE_ID"
              value: "2"
            -
              name: "NODE_NAME"
              value: "node2"
            -
              name: "CLUSTER_NODE_NETWORK_NAME"
              value: "gnresolver-db-slave1-service"
            -
              name: "REPMGR_WAIT_POSTGRES_START_TIMEOUT"
              valueFrom:
                configMapKeyRef:
                  name: gnresolver
                  key: db.repmgr.timeout

            # Cluster configs
            - name: "CLUSTER_NAME"
              valueFrom:
                configMapKeyRef:
                  name: gnresolver
                  key: db.cluster.name
            - name: "REPLICATION_DB"
              valueFrom:
                configMapKeyRef:
                  name: gnresolver
                  key: db.cluster.replication.db
            - name: "REPLICATION_USER"
              valueFrom:
                secretKeyRef:
                  name: gnresolver
                  key: db.cluster.replication.user
            - name: "REPLICATION_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: gnresolver
                  key: db.cluster.replication.user.password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath:  /var/lib/postgresql/data
              name: gnresolver-db-slave-vol
